spring:
  config:
    import: optional:application-secret.yml
  #  sql:
  #    init:
  #      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    defer-datasource-initialization: true
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false
      timeout: 2000

# Swagger configurations
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path:
    operations-sorter: alpha


app:
  auth:
    token-secret: lNLp8m5m86mRQLgNU7UnhGqfBbNdNYAM45YOFwZmP1w=
    refresh-token-expiration-milliseconds: 1209600000  # 14 days
    access-token-expiration-milliseconds: 86400000  # 24 hours
    reset-token-expiration-milliseconds: 300000
    register-token-expiration-milliseconds: 300000