server:
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  application:
    name: cinema-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    active: prod